<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Dockerfile" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.25" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.25" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="8.0.3" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskFlowApi.Application\TaskFlowApi.Application.csproj" />
    <ProjectReference Include="..\TaskFlowApi.Domain\TaskFlowApi.Domain.csproj" />
    <ProjectReference Include="..\TaskFlowApi.infra\TaskFlowApi.infra.csproj" />
  </ItemGroup>

</Project>
